'use client';
import {useRef,useState} from 'react';
import {ChevronLeft,ChevronRight} from 'lucide-react';
export type MediaSlide={type:'image'|'video'|'text'|'audio';src?:string;text?:string};
export function PhotoCarousel({images=[],author,media=[]}:{images?:string[];author:string;media?:MediaSlide[]}){
 const slides:MediaSlide[]=media.length?media:images.map(src=>({type:'image',src}));
 const [index,setIndex]=useState(0);const track=useRef<HTMLDivElement>(null);
 const go=(i:number)=>track.current?.scrollTo({left:(track.current.children[i] as HTMLElement)?.offsetLeft||0,behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});
 if(!slides.length)return null;
 return <div className="photo-carousel"><div className="photo-track" ref={track} onScroll={e=>{const node=e.currentTarget;const step=(node.children[0] as HTMLElement)?.offsetWidth+(parseFloat(getComputedStyle(node).columnGap)||0);const next=Math.min(slides.length-1,Math.round(node.scrollLeft/(step||node.clientWidth)));setIndex(next);node.querySelectorAll('video,audio').forEach(player=>{if(!(node.children[next]?.contains(player)))(player as HTMLMediaElement).pause()})}}>{slides.map((slide,i)=><div className={'photo-slide media-'+slide.type} key={i}>{slide.type==='image'?<img src={(slide.src?.startsWith('data:image/')||slide.src?.startsWith('/'))?slide.src:'/products/'+slide.src+'.jpg'} alt={`Product photo ${i+1} shared by ${author}`} loading="lazy"/>:slide.type==='video'?<video controls playsInline preload="metadata" src={slide.src} aria-label={`Video shared by ${author}`}/>:slide.type==='audio'?<div className="audio-slide"><strong>Voice note</strong><audio controls preload="metadata" src={slide.src} aria-label={`Voice note by ${author}`}/></div>:<p className="text-slide">{slide.text}</p>}</div>)}</div>{slides.length>1&&<><span className="photo-count">{index+1}/{slides.length}</span><button className="photo-prev" aria-label="Previous media" disabled={index===0} onClick={()=>go(index-1)}><ChevronLeft size={18}/></button><button className="photo-next" aria-label="Next media" disabled={index===slides.length-1} onClick={()=>go(index+1)}><ChevronRight size={18}/></button><div className="photo-dots">{slides.map((_,i)=><button key={i} className={index===i?'active':''} aria-label={`Media ${i+1}`} aria-current={index===i?'true':undefined} onClick={()=>go(i)}/>)}</div></>}</div>
}
